name: "기능 추가"
description: "새로운 기능 추가"
title: "[FEAT] "
labels: ["feat"]
body:
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
