# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '16.1'
        
    - name: Check XCode version
      run: xcodebuild -version
      
    - name: List available Simulators
      run: xcrun simctl list
      
    - uses: actions/checkout@v4
    
    - name: UnitTest run
      run: |
        xcodebuild clean test \
        -project Qapple/Qapple.xcodeproj \
        -scheme QappleTests \
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
        -skipMacroValidation
