# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Set up XCode
      uses: maxim-lobanov/setup-xcode@v2
      with:
        xcode-version: '16.0'
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild clean test -project Qapple/Qapple.xcodeproj -scheme Qapple
